export interface PricingTier {
  name: string
  price: number | "Custom"
  period: "month" | "year" | "one-time"
  features: string[]
  popular?: boolean
}

export type ToolCategory =
  | "Website Builder"
  | "E-commerce"
  | "Marketing"
  | "Design"
  | "Analytics"
  | "Automation"
  | "Database"
  | "CMS"
  | "AI & LLM"
  | "Payment Processing"

export interface Tool {
  name: string
  slug: string
  tagline: string
  description: string
  longDescription: string
  logo: string
  category: ToolCategory
  subcategories?: string[]
  pricingModel: "Free" | "Freemium" | "Paid"
  pricingTiers: PricingTier[]
  features: string[]
  integrations?: string[]
  screenshots?: string[]
  affiliateLink: string
  websiteUrl: string
  rating: number
  reviewCount: number
  alternatives?: string[]
  popular?: boolean
  new?: boolean
  verified?: boolean
}

export const TOOLS: Tool[] = [
  {
    name: "Framer",
    slug: "framer",
    tagline: "Design and publish your dream site. Zero code, maximum speed.",
    description: "The internet is your canvas. Design and publish modern sites with Framer's powerful visual editor and CMS.",
    longDescription: "Framer is a professional website builder that combines design and code. Create responsive websites with an intuitive interface, built-in CMS, and powerful animations. Perfect for designers and teams who want full creative control without writing code.",
    logo: "https://framerusercontent.com/images/48ha9K9kLd2q3g.png",
    category: "Website Builder",
    subcategories: ["Design", "CMS", "Animation"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["1 site", "Framer subdomain", "Community support"] },
      { name: "Mini", price: 5, period: "month", features: ["1 site per project", "Custom domain", "Performance insights"], popular: true },
      { name: "Basic", price: 15, period: "month", features: ["Unlimited sites", "10,000 CMS items", "Staging environments"] },
    ],
    features: ["Visual Editor", "Built-in CMS", "Advanced Animations", "Responsive Design", "SEO Tools", "Components Library"],
    integrations: ["Google Analytics", "Mailchimp", "Zapier", "Airtable"],
    affiliateLink: "https://framer.com",
    websiteUrl: "https://framer.com",
    rating: 4.8,
    reviewCount: 1247,
    alternatives: ["webflow", "wix", "squarespace"],
    popular: true,
    verified: true,
  },
  {
    name: "Webflow",
    slug: "webflow",
    tagline: "Build with the power of code — without writing any.",
    description: "The site builder for professional designers. Design, build, and launch responsive websites visually.",
    longDescription: "Webflow empowers designers to build professional, custom websites in a visual canvas — no coding required. Add interactions and animations, connect to a CMS, and publish to fast, secure hosting.",
    logo: "https://assets-global.website-files.com/659dbf403906721310292148/659dbf403906721310292148_opengraph.png",
    category: "Website Builder",
    subcategories: ["CMS", "E-commerce", "Design"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["2 projects", "webflow.io subdomain", "Limited CMS items"] },
      { name: "Basic", price: 14, period: "month", features: ["Custom domain", "Faster CDN", "Form submissions"], popular: true },
      { name: "CMS", price: 23, period: "month", features: ["2,000 CMS items", "3 editors", "Search functionality"] },
      { name: "Business", price: 39, period: "month", features: ["10,000 CMS items", "10 editors", "Advanced SEO"] },
    ],
    features: ["Visual CMS", "Ecommerce", "Interactions & Animations", "Responsive Breakpoints", "Custom Code", "Form Builder"],
    integrations: ["Zapier", "Google Analytics", "Mailchimp", "Stripe"],
    affiliateLink: "https://webflow.com",
    websiteUrl: "https://webflow.com",
    rating: 4.6,
    reviewCount: 2134,
    alternatives: ["framer", "wix", "wordpress"],
    popular: true,
    verified: true,
  },
  {
    name: "Shopify",
    slug: "shopify",
    tagline: "The global commerce platform to build your business.",
    description: "Everything you need to sell online, in-store, and everywhere in between.",
    longDescription: "Shopify is a complete commerce platform that lets you start, grow, and manage a business. Create and customize an online store, sell in multiple places, and manage products, inventory, payments, and shipping.",
    logo: "https://cdn.shopify.com/assets/images/logos/shopify-bag.png",
    category: "E-commerce",
    subcategories: ["Storefront", "POS", "Payments"],
    pricingModel: "Paid",
    pricingTiers: [
      { name: "Basic", price: 29, period: "month", features: ["Online store", "Unlimited products", "24/7 support"], popular: true },
      { name: "Shopify", price: 79, period: "month", features: ["Professional reports", "5 staff accounts", "Lower fees"] },
      { name: "Advanced", price: 299, period: "month", features: ["Advanced reports", "15 staff accounts", "Lowest fees"] },
    ],
    features: ["Online Store", "POS System", "Payment Processing", "Inventory Management", "Marketing Tools", "Analytics"],
    integrations: ["Facebook", "Instagram", "Amazon", "Google Shopping", "Mailchimp"],
    affiliateLink: "https://shopify.com",
    websiteUrl: "https://shopify.com",
    rating: 4.7,
    reviewCount: 5642,
    alternatives: ["woocommerce", "bigcommerce", "squarespace"],
    popular: true,
    verified: true,
  },
  {
    name: "Canva",
    slug: "canva",
    tagline: "Design anything. Publish anywhere.",
    description: "Create professional designs with Canva's drag-and-drop editor and thousands of templates.",
    longDescription: "Canva is a free-to-use online graphic design tool. Use it to create social media posts, presentations, posters, videos, logos and more. With thousands of templates, images, and design elements.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg",
    category: "Design",
    subcategories: ["Graphics", "Templates", "Collaboration"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["250,000+ templates", "100+ design types", "Mobile apps"] },
      { name: "Pro", price: 12.99, period: "month", features: ["100M+ premium stock", "Magic Resize", "Brand Kit", "Background Remover"], popular: true },
      { name: "Teams", price: 30, period: "month", features: ["Everything in Pro", "Team collaboration", "Brand controls"] },
    ],
    features: ["Templates", "Stock Photos", "Drag & Drop Editor", "Collaboration", "Brand Kit", "Social Media Scheduler"],
    integrations: ["Google Drive", "Dropbox", "Facebook", "Instagram", "Mailchimp"],
    affiliateLink: "https://canva.com",
    websiteUrl: "https://canva.com",
    rating: 4.7,
    reviewCount: 8234,
    alternatives: ["figma", "adobe-express", "vistacreate"],
    popular: true,
    verified: true,
  },
  {
    name: "Zapier",
    slug: "zapier",
    tagline: "Automate your work across 6,000+ app integrations.",
    description: "Easy automation for busy people. Zapier moves info between your web apps automatically.",
    longDescription: "Zapier lets you connect your apps and automate workflows. Build custom automations without code using a simple visual interface. Connect 6,000+ apps to automate repetitive tasks and save time.",
    logo: "https://cdn.zapier.com/zapier/images/logos/zapier-logo.png",
    category: "Automation",
    subcategories: ["Workflow", "Integration", "No-code"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["100 tasks/month", "5 Zaps", "15 min updates"] },
      { name: "Starter", price: 19.99, period: "month", features: ["750 tasks/month", "20 Zaps", "Multi-step Zaps"], popular: true },
      { name: "Professional", price: 49, period: "month", features: ["2,000 tasks/month", "Unlimited Zaps", "Webhooks"] },
    ],
    features: ["6,000+ Integrations", "Multi-step Zaps", "Conditional Logic", "Webhooks", "Custom Logic", "Team Collaboration"],
    integrations: ["Gmail", "Slack", "Google Sheets", "Airtable", "Notion"],
    affiliateLink: "https://zapier.com",
    websiteUrl: "https://zapier.com",
    rating: 4.5,
    reviewCount: 3421,
    alternatives: ["make", "n8n", "integromat"],
    popular: true,
    verified: true,
  },
  {
    name: "Make",
    slug: "make",
    tagline: "Design, build, and automate anything for your work.",
    description: "Visual platform to design, build, and automate anything—from simple tasks to complex workflows.",
    longDescription: "Make (formerly Integromat) lets you design, build, and automate anything from tasks and workflows to apps and systems. Connect apps and services with a visual builder.",
    logo: "https://www.make.com/en/home/_next/static/media/logo.svg",
    category: "Automation",
    subcategories: ["Workflow", "Integration", "API"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["1,000 operations", "15 min intervals", "2 active scenarios"] },
      { name: "Core", price: 9, period: "month", features: ["10,000 operations", "5 min intervals", "Unlimited scenarios"], popular: true },
      { name: "Pro", price: 16, period: "month", features: ["10,000 operations", "1 min intervals", "Priority support"] },
    ],
    features: ["Visual Builder", "HTTP/API Requests", "Error Handling", "Data Stores", "Webhooks", "Scheduling"],
    integrations: ["Google Workspace", "Slack", "Airtable", "Notion", "HTTP/REST APIs"],
    affiliateLink: "https://www.make.com",
    websiteUrl: "https://www.make.com",
    rating: 4.6,
    reviewCount: 1876,
    alternatives: ["zapier", "n8n", "activepieces"],
    popular: true,
    verified: true,
  },
  {
    name: "Notion",
    slug: "notion",
    tagline: "Your wiki, docs & projects. Together.",
    description: "One workspace for your notes, tasks, wikis, and databases.",
    longDescription: "Notion is the all-in-one workspace for notes, tasks, wikis, and databases. Customize your workspace with flexible building blocks to create the workflow you want.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
    category: "CMS",
    subcategories: ["Productivity", "Collaboration", "Database"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["Individual use", "Unlimited pages & blocks", "7 day page history"] },
      { name: "Plus", price: 8, period: "month", features: ["Unlimited file uploads", "30 day page history", "Invite guests"], popular: true },
      { name: "Business", price: 15, period: "month", features: ["SAML SSO", "Advanced permissions", "90 day history"] },
    ],
    features: ["Databases", "Wikis", "Docs", "Projects", "Templates", "Real-time Collaboration"],
    integrations: ["Slack", "Google Drive", "Figma", "GitHub", "Zapier"],
    affiliateLink: "https://notion.so",
    websiteUrl: "https://notion.so",
    rating: 4.7,
    reviewCount: 4521,
    alternatives: ["airtable", "coda", "clickup"],
    popular: true,
    verified: true,
  },
  {
    name: "Airtable",
    slug: "airtable",
    tagline: "Build powerful work apps, without coding.",
    description: "Part spreadsheet, part database, totally flexible. Organize anything with Airtable.",
    longDescription: "Airtable is a low-code platform to build next-gen apps. Move beyond rigid tools, operationalize your critical data, and reimagine workflows with AI.",
    logo: "https://static.airtable.com/images/logo.png",
    category: "Database",
    subcategories: ["Spreadsheet", "No-code", "Collaboration"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["Unlimited bases", "1,200 records per base", "1 GB attachments"] },
      { name: "Plus", price: 10, period: "month", features: ["5,000 records per base", "5 GB attachments", "6 month history"], popular: true },
      { name: "Pro", price: 20, period: "month", features: ["50,000 records per base", "20 GB attachments", "Extensions"] },
    ],
    features: ["Grid View", "Forms", "Kanban", "Calendar", "Gantt", "Automations", "Integrations"],
    integrations: ["Slack", "Google Workspace", "Salesforce", "Zapier", "Make"],
    affiliateLink: "https://airtable.com",
    websiteUrl: "https://airtable.com",
    rating: 4.6,
    reviewCount: 2987,
    alternatives: ["notion", "coda", "smartsheet"],
    popular: true,
    verified: true,
  },
  {
    name: "Stripe",
    slug: "stripe",
    tagline: "Financial infrastructure for the internet.",
    description: "Millions of companies use Stripe to accept payments and manage their businesses online.",
    longDescription: "Stripe is a technology company that builds economic infrastructure for the internet. Businesses of every size use our software to accept payments and manage their businesses online.",
    logo: "https://images.ctfassets.net/fzn2n1nzq965/3AGidihOJl4nH9D1vDjM84/9540155d584be52fc54c443b6efa4ae6/stripe.png",
    category: "Payment Processing",
    subcategories: ["Payments", "Billing", "API"],
    pricingModel: "Paid",
    pricingTiers: [
      { name: "Integrated", price: 0, period: "month", features: ["2.9% + 30¢ per transaction", "No monthly fee", "Full API access"], popular: true },
    ],
    features: ["Payment Processing", "Subscriptions", "Invoicing", "Radar Fraud Prevention", "Connect Platform", "Terminal POS"],
    integrations: ["Shopify", "WooCommerce", "Squarespace", "Salesforce"],
    affiliateLink: "https://stripe.com",
    websiteUrl: "https://stripe.com",
    rating: 4.5,
    reviewCount: 3214,
    alternatives: ["paypal", "square", "braintree"],
    verified: true,
  },
  {
    name: "Mailchimp",
    slug: "mailchimp",
    tagline: "Turn emails into revenue.",
    description: "Grow your business with the #1 email marketing and automation platform.",
    longDescription: "Mailchimp is an all-in-one marketing platform for small businesses. Create email campaigns, automate messages, and build targeted audiences with powerful analytics.",
    logo: "https://eep.io/images/yzco4xsimv0y/6G1j288888888888888888/44444444444444444444444444444444/Mailchimp-Logo.png",
    category: "Marketing",
    subcategories: ["Email", "Automation", "CRM"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["500 contacts", "1,000 sends/month", "Basic templates"] },
      { name: "Essentials", price: 13, period: "month", features: ["50,000 contacts", "Automation", "A/B testing"], popular: true },
      { name: "Standard", price: 20, period: "month", features: ["100,000 contacts", "Advanced segmentation", "Retargeting ads"] },
    ],
    features: ["Email Campaigns", "Marketing Automation", "Landing Pages", "CRM", "Analytics", "Segmentation"],
    integrations: ["Shopify", "WooCommerce", "Salesforce", "Canva", "Zapier"],
    affiliateLink: "https://mailchimp.com",
    websiteUrl: "https://mailchimp.com",
    rating: 4.3,
    reviewCount: 6421,
    alternatives: ["convertkit", "sendinblue", "activecampaign"],
    verified: true,
  },
  {
    name: "Carrd",
    slug: "carrd",
    tagline: "Simple, free, fully responsive one-page sites.",
    description: "Build beautiful one-page sites for pretty much anything in minutes.",
    longDescription: "Carrd is a simple, free platform for building one-page sites for anything. Whether it's a landing page, profile, or portfolio, Carrd has you covered.",
    logo: "https://carrd.co/assets/images/share.jpg",
    category: "Website Builder",
    subcategories: ["Landing Pages", "Portfolio", "Simple"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["3 sites", "carrd.co subdomain", "Basic elements"] },
      { name: "Pro Lite", price: 9, period: "year", features: ["10 sites", "Custom domains", "Forms"], popular: true },
      { name: "Pro Standard", price: 19, period: "year", features: ["25 sites", "Premium elements", "Embeds"] },
    ],
    features: ["One-page Sites", "Responsive Design", "Forms", "Custom Domains", "Google Analytics", "Widgets"],
    affiliateLink: "https://carrd.co",
    websiteUrl: "https://carrd.co",
    rating: 4.8,
    reviewCount: 892,
    alternatives: ["linktree", "bio-fm", "beacons"],
    popular: false,
    verified: true,
  },
  {
    name: "Gumroad",
    slug: "gumroad",
    tagline: "Sell what you know. It's that easy.",
    description: "Super-simple e-commerce for creators. Sell digital products directly to your audience.",
    longDescription: "Gumroad is a self-publishing digital marketplace platform that facilitates the sale of products by creators directly to consumers.",
    logo: "https://assets.gumroad.com/assets/og-image-64c51c2d2d2d2d2d2d2d2d2d2d2d2d2d.png",
    category: "E-commerce",
    subcategories: ["Digital Products", "Creators", "Memberships"],
    pricingModel: "Free",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["10% fee per sale", "Instant payouts", "Email marketing"], popular: true },
      { name: "Premium", price: 10, period: "month", features: ["Only 3.5% + 30¢ fee", "No additional percentage", "Advanced customization"] },
    ],
    features: ["Digital Downloads", "Memberships", "Subscriptions", "Email Marketing", "License Keys", "Pay What You Want"],
    affiliateLink: "https://gumroad.com",
    websiteUrl: "https://gumroad.com",
    rating: 4.4,
    reviewCount: 1234,
    alternatives: ["payhip", "sellfy", "lemonsqueezy"],
    verified: true,
  },
  {
    name: "Figma",
    slug: "figma",
    tagline: "Where teams design together.",
    description: "The collaborative interface design tool. Build better products as a team.",
    longDescription: "Figma is a collaborative interface design tool that helps teams create, test, and ship better designs from start to finish. Design, prototype, and gather feedback all in one place.",
    logo: "https://cdn.sanity.io/images/599r6htc/localized/46a76c802176eb17b04e12108de7e7e0f3736dc6-1024x1024.png",
    category: "Design",
    subcategories: ["UI/UX", "Prototyping", "Collaboration"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Starter", price: 0, period: "month", features: ["3 Figma files", "3 FigJam files", "Unlimited collaborators"] },
      { name: "Professional", price: 12, period: "month", features: ["Unlimited files", "Version history", "Private projects"], popular: true },
      { name: "Organization", price: 45, period: "month", features: ["Design systems", "Branching", "Libraries"] },
    ],
    features: ["Vector Tools", "Prototyping", "Design Systems", "Comments", "Plugins", "Dev Mode"],
    integrations: ["Slack", "Miro", "Notion", "Jira", "Asana"],
    affiliateLink: "https://figma.com",
    websiteUrl: "https://figma.com",
    rating: 4.8,
    reviewCount: 7654,
    alternatives: ["sketch", "adobe-xd", "penpot"],
    popular: true,
    verified: true,
  },
  {
    name: "Google Analytics",
    slug: "google-analytics",
    tagline: "Understand your customers.",
    description: "Free tools to analyze data for your business in one place. Make smarter decisions.",
    longDescription: "Google Analytics gives you the tools you need to better understand your customers. You can then use those business insights to take action, such as improving your website, creating tailored audience lists, and more.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/w/w9/Google_Analytics_logo.svg/1200px-Google_Analytics_logo.svg.png",
    category: "Analytics",
    subcategories: ["Web Analytics", "Tracking", "Reporting"],
    pricingModel: "Free",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["Unlimited reporting", "10M hits/month", "Standard reports"], popular: true },
      { name: "Analytics 360", price: "Custom", period: "month", features: ["150M hits/month", "Advanced analysis", "SLA & support"] },
    ],
    features: ["Real-time Reporting", "Audience Insights", "Custom Reports", "Goals & Conversions", "E-commerce Tracking", "Attribution"],
    integrations: ["Google Ads", "Search Console", "BigQuery", "Data Studio"],
    affiliateLink: "https://analytics.google.com",
    websiteUrl: "https://analytics.google.com",
    rating: 4.5,
    reviewCount: 12453,
    alternatives: ["plausible", "fathom", "matomo"],
    verified: true,
  },
  {
    name: "Bubble",
    slug: "bubble",
    tagline: "Build powerful web apps without code.",
    description: "The most powerful no-code platform for creating digital products. Build apps at lightning speed.",
    longDescription: "Bubble is a visual programming language that lets you build web applications without code. Design your app's interface, build workflows, manage databases, and deploy to production—all in your browser.",
    logo: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_f0b606abb6d19089febc9faeeba5bc05/bubble.png",
    category: "Website Builder",
    subcategories: ["No-code", "Web Apps", "Database"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["Bubble subdomain", "Limited capacity", "Bubble branding"] },
      { name: "Starter", price: 29, period: "month", features: ["Custom domain", "Increased capacity", "Remove branding"], popular: true },
      { name: "Growth", price: 119, period: "month", features: ["Production & Development apps", "Priority support", "Advanced features"] },
    ],
    features: ["Visual Editor", "Database", "Workflows", "API Connector", "Plugins", "Responsive Design"],
    integrations: ["Stripe", "SendGrid", "API Integration", "OAuth"],
    affiliateLink: "https://bubble.io",
    websiteUrl: "https://bubble.io",
    rating: 4.5,
    reviewCount: 2341,
    alternatives: ["webflow", "adalo", "flutterflow"],
    popular: true,
    verified: true,
  },
  {
    name: "Supabase",
    slug: "supabase",
    tagline: "The open source Firebase alternative.",
    description: "Build production-grade applications with a Postgres database, authentication, and storage.",
    longDescription: "Supabase is an open source Firebase alternative. Start your project with a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, and Storage.",
    logo: "https://supabase.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsupabase-logo-wordmark--light.b36010cf.png",
    category: "Database",
    subcategories: ["Backend", "Authentication", "Storage"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["500 MB database", "50,000 monthly active users", "5 GB bandwidth"] },
      { name: "Pro", price: 25, period: "month", features: ["8 GB database", "100,000 MAU", "50 GB bandwidth"], popular: true },
      { name: "Team", price: 599, period: "month", features: ["Dedicated support", "SLA", "SSO"] },
    ],
    features: ["Postgres Database", "Authentication", "Storage", "Realtime", "Edge Functions", "Vector Embeddings"],
    integrations: ["Vercel", "Next.js", "React", "Flutter"],
    affiliateLink: "https://supabase.com",
    websiteUrl: "https://supabase.com",
    rating: 4.7,
    reviewCount: 1876,
    alternatives: ["firebase", "appwrite", "pocketbase"],
    popular: true,
    new: true,
    verified: true,
  },
  {
    name: "ChatGPT Plus",
    slug: "chatgpt-plus",
    tagline: "Get faster responses and access to GPT-4.",
    description: "Upgrade to ChatGPT Plus for faster responses, priority access, and GPT-4.",
    longDescription: "ChatGPT Plus gives you access to GPT-4, faster response times, and priority access during peak hours. Build custom GPTs, generate images with DALL-E, and access the latest features first.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png",
    category: "AI & LLM",
    subcategories: ["Language Model", "Chatbot", "Code Generation"],
    pricingModel: "Paid",
    pricingTiers: [
      { name: "Plus", price: 20, period: "month", features: ["GPT-4 access", "Faster responses", "Priority access", "DALL-E 3"], popular: true },
    ],
    features: ["GPT-4 Access", "Custom GPTs", "DALL-E 3", "Code Interpreter", "Web Browsing", "Plugins"],
    affiliateLink: "https://openai.com/chatgpt",
    websiteUrl: "https://openai.com/chatgpt",
    rating: 4.6,
    reviewCount: 8934,
    alternatives: ["claude-pro", "gemini-advanced", "copilot"],
    popular: true,
    new: false,
    verified: true,
  },
  {
    name: "Wix",
    slug: "wix",
    tagline: "Create a website you're proud of.",
    description: "Build and grow your brand with the leading website builder trusted by 230M+ users worldwide.",
    longDescription: "Wix is a cloud-based web development platform with millions of users worldwide. Create a professional website with the Wix website builder, complete with powerful SEO tools and integrated marketing solutions.",
    logo: "https://static.wixstatic.com/media/9ab0d1_3c2490ed554d48cc863a75f2c8f1e48f~mv2.png",
    category: "Website Builder",
    subcategories: ["Drag & Drop", "Templates", "E-commerce"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["Wix subdomain", "500 MB storage", "Wix ads"] },
      { name: "Combo", price: 16, period: "month", features: ["Connect domain", "3 GB storage", "Remove ads"], popular: true },
      { name: "Unlimited", price: 22, period: "month", features: ["10 GB storage", "Visitor analytics", "Site booster"] },
      { name: "Business Basic", price: 27, period: "month", features: ["Accept payments", "Custom domain", "50 GB storage"] },
    ],
    features: ["Drag & Drop Editor", "500+ Templates", "Mobile Optimization", "SEO Tools", "App Market", "24/7 Support"],
    integrations: ["Google", "Facebook", "Mailchimp", "PayPal"],
    affiliateLink: "https://wix.com",
    websiteUrl: "https://wix.com",
    rating: 4.2,
    reviewCount: 9234,
    alternatives: ["squarespace", "weebly", "webflow"],
    popular: true,
    verified: true,
  },
  {
    name: "ConvertKit",
    slug: "convertkit",
    tagline: "The creator marketing platform.",
    description: "Email marketing for online creators. Grow your audience and earn a living doing work you love.",
    longDescription: "ConvertKit is an email marketing platform built for creators. Send beautiful emails, automate your marketing, sell digital products, and grow your audience—all from one place.",
    logo: "https://convertkit.com/wp-content/themes/convertkit/assets/images/ck-logo-white.svg",
    category: "Marketing",
    subcategories: ["Email", "Automation", "Creators"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Free", price: 0, period: "month", features: ["Up to 1,000 subscribers", "Unlimited landing pages", "Email broadcasts"] },
      { name: "Creator", price: 29, period: "month", features: ["3,000 subscribers", "Automated funnels", "Premium templates"], popular: true },
      { name: "Creator Pro", price: 59, period: "month", features: ["Newsletter referral system", "Advanced reporting", "Priority support"] },
    ],
    features: ["Email Campaigns", "Visual Automations", "Landing Pages", "Subscriber Scoring", "Integrations", "Commerce"],
    integrations: ["Shopify", "WordPress", "Zapier", "Teachable"],
    affiliateLink: "https://convertkit.com",
    websiteUrl: "https://convertkit.com",
    rating: 4.5,
    reviewCount: 2134,
    alternatives: ["mailchimp", "activecampaign", "sendinblue"],
    verified: true,
  },
  {
    name: "Lemon Squeezy",
    slug: "lemon-squeezy",
    tagline: "Payments, tax & subscriptions for software companies.",
    description: "All-in-one platform for running your SaaS business. Payments, subscriptions, and global tax compliance.",
    longDescription: "Lemon Squeezy is an all-in-one platform for running your software business. Accept payments, manage subscriptions, and stay compliant with global tax laws—all from one beautiful dashboard.",
    logo: "https://www.lemonsqueezy.com/assets/brand/logo-dark.svg",
    category: "Payment Processing",
    subcategories: ["Payments", "Subscriptions", "Tax"],
    pricingModel: "Paid",
    pricingTiers: [
      { name: "Standard", price: 0, period: "month", features: ["5% + 50¢ per transaction", "Global tax compliance", "Fraud prevention"], popular: true },
    ],
    features: ["Payment Processing", "Subscription Management", "Tax Compliance", "Email Marketing", "Affiliate Program", "License Keys"],
    integrations: ["Zapier", "Discord", "Slack", "Webhooks"],
    affiliateLink: "https://lemonsqueezy.com",
    websiteUrl: "https://lemonsqueezy.com",
    rating: 4.7,
    reviewCount: 543,
    alternatives: ["gumroad", "paddle", "stripe"],
    popular: true,
    new: true,
    verified: true,
  },
  {
    name: "Vercel",
    slug: "vercel",
    tagline: "Develop. Preview. Ship.",
    description: "The platform for frontend developers. Deploy web projects with zero configuration.",
    longDescription: "Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration. Deploy with zero configuration, collaborate with ease.",
    logo: "https://assets.vercel.com/image/upload/front/favicon/vercel/180x180.png",
    category: "Website Builder",
    subcategories: ["Hosting", "Deployment", "Serverless"],
    pricingModel: "Freemium",
    pricingTiers: [
      { name: "Hobby", price: 0, period: "month", features: ["100 GB bandwidth", "Serverless functions", "Web analytics"] },
      { name: "Pro", price: 20, period: "month", features: ["1 TB bandwidth", "Password protection", "Team collaboration"], popular: true },
      { name: "Enterprise", price: "Custom", period: "month", features: ["Custom limits", "SLA", "Dedicated support"] },
    ],
    features: ["Instant Deployments", "Serverless Functions", "Edge Network", "Analytics", "Preview Deployments", "Git Integration"],
    integrations: ["GitHub", "GitLab", "Bitbucket", "Next.js"],
    affiliateLink: "https://vercel.com",
    websiteUrl: "https://vercel.com",
    rating: 4.7,
    reviewCount: 2876,
    alternatives: ["netlify", "cloudflare-pages", "railway"],
    popular: true,
    verified: true,
  },
]
